#!/bin/bash
# https://github.com/a18pauenjsum/projecte-01
#Programa per creació d'usuaris
#Filtre de root
echo "El teu UID és ${UID}"
if [[ "${UID}" -eq 0 ]]; then
  echo 'Ets root.'
  #Demana el nom de l'usuari
  read -p 'Dona`m el nom d`usuari: ' USER_NAME
  #Demana el nom real.
  read -p 'Dona`m el teu nom real: ' COMMENT
  #Demanar la password
  read -p 'Dona`m la contrasenya: ' PASSWORD
  # Creació de l'usuari.
  useradd -c "${COMMENT}" -m ${USER_NAME}
  if [[ "${?}" -ne 0 ]]; then
    echo 'Hi hagut un error.'
  else
    echo 'Ha estat executat correctament.'
    echo "El teu nom d'usuari és ${USER_NAME}"
    if [[ "${?}" -ne 0 ]]; then
      echo 'Hi hagut un error.'
    else
      echo "Canvi de pass ok ${PASSWORD}"
      #Oblicació de canviar pass en el primer log
      passwd -e ${USER_NAME}
      #Mostra el username, password, host
      echo "El teu nom d'usuari és: ". ${USER_NAME}
      echo "La teva contrasenya és: ". ${PASSWORD}
      echo "El teu host és: ". ${HOSTNAME}
    fi
  fi
else
  echo 'No ets root.'
fi
